### ISSUE TITLE
脚本可以使用，但是百度无法访问，外网也没问题

### ISSUE THREAD

**Issue by ChengZ996** [thisIsIan-W/homeproxy-autogen-configuration#1]
脚本可以使用，但是百度无法访问，外网也没问题

**Comment by thisIsIan-W** [comment]
贴出具体配置。

**Comment by ChengZ996** [comment]
[homeproxy (2).txt](https://github.com/user-attachments/files/16751122/homeproxy.2.txt)

**Comment by ChengZ996** [comment]
配置文件已上传  
![WeChat截图_20240827001907](https://github.com/user-attachments/assets/0a4f9319-f9c1-457a-ae84-181d8f7b3477)
![Snipaste_2024-08-27_00-19-15](https://github.com/user-attachments/assets/6bb2dde3-2e5c-4f8f-807c-c3aac8442690)
![Snipaste_2024-08-27_00-19-27](https://github.com/user-attachments/assets/b9de6887-2f80-432b-83e3-07afd9d066f4)
![WeChat截图_20240827001953](https://github.com/user-attachments/assets/488ec9c1-aa5d-4568-b4c3-11d8db59dc16)
![WeChat截图_20240827001848](https://github.com/user-attachments/assets/956c8dad-60b4-4d98-8a58-655322f779f0)
![Snipaste_2024-08-27_00-19-01](https://github.com/user-attachments/assets/28edb13b-a3d4-45af-918d-ad306f210992)

**Comment by ChengZ996** [comment]
所以的节点都配置为订阅。

**Comment by ChengZ996** [comment]
环境是旁路由。
开启了绕过中国，百度可以了，但是Microsoft官网没有开启

**Comment by thisIsIan-W** [comment]
配置与界面预期不符，请仔细阅读操作手册！
