### ISSUE TITLE
有没有简单的方法复制 默认 gfwlist 模式的设置 到自定义模式下？

### ISSUE THREAD

**Issue by ATang007ZH** [thisIsIan-W/homeproxy-autogen-configuration#11]
有没有简单的方法复制 默认 gfwlist 模式的设置 到自定义模式下？

因为现在用的这个模式基本够用了，在摸索更进阶的玩法。比如想试试 urltest 节点自动选择功能，必须切换到自定义模式下。
自定义模式全是空的看着都懵了，如果能复制 某个模式（比如gfwlist 模式）的设置过来，就可以边用边试了。

**Comment by thisIsIan-W** [comment]
你可以自己fork仓库实现需求
