### ISSUE TITLE
当自定义规则集存在 ! 时会导致生成的homeproxy无法被读取

### ISSUE THREAD

**Issue by ngnlAYY** [thisIsIan-W/homeproxy-autogen-configuration#3]
例如geolocation-!cn.srs规则集
![1](https://github.com/user-attachments/assets/0e47cea3-a320-4614-8b52-703ebb17f3e7)
![2](https://github.com/user-attachments/assets/c101d511-1a86-4ed7-a56d-7603f4342db4)
![3](https://github.com/user-attachments/assets/51a32c87-fb37-4b0c-a03d-101e53a8f270)

**Comment by thisIsIan-W** [comment]
已解决，详见 [#249ea6c](https://github.com/thisIsIan-W/homeproxy-autogen-configuration/commit/249ea6c548cdd2891afcc1ca3de635d83bc441e2)
