### ISSUE TITLE
你好  执行bash homeproxy_rules.sh sh的时候报错

### ISSUE THREAD

**Issue by 142857X1** [thisIsIan-W/homeproxy-autogen-configuration#4]
bash homeproxy_rules.sh

homeproxy_rules.sh: line 7: syntax error near unexpected token `newline'
homeproxy_rules.sh: line 7: `<!DOCTYPE html>'

**Comment by thisIsIan-W** [comment]
1. 确认你执行的 homeproxy_rules.sh 没有经过任何修改；
2. 确认你上传到设备上的脚本的编码为 UTF8 以及格式为 LF(UNIX)；
3. 请按照wiki上的步骤先行排错；
4. 如果上述步骤无法解决你的问题，请提供更多报错信息以及上传你执行的脚本文件到本issue
