### ISSUE TITLE
ipv6报错

### ISSUE THREAD

**Issue by tao917922822** [thisIsIan-W/homeproxy-autogen-configuration#6]
![Screenshot_2024-10-30-10-34-32-314_mark via](https://github.com/user-attachments/assets/cf44ae7c-0eef-4fde-8ceb-a597978f5a87)
所有能关闭ipv6的方法都试过了  还是不行  本来宽带就不支持ipv6  代理服务器一请求ipv6就断网

**Comment by tao917922822** [comment]
服务器刚升级两天  ipv6和ipv4  防火墙设置什么的都试过了 彻底关闭了ipv6的  但是就这个问题  游戏玩着玩着就掉线了  打开后台一看  就这些报错

**Comment by thisIsIan-W** [comment]
自行检查原因。
